name: sse_dart_client
description: Use this package to manage SSE Client connections
version: 1.0.5
homepage: https://github.com/astudilloalex/flutter-alex-astudillo-packages-apps
repository: https://github.com/astudilloalex/flutter-alex-astudillo-packages-apps/tree/main/packages/sse_client

environment:
  sdk: ">=3.1.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
